
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'fa' | 'en' | 'ar' | 'sv' | 'tr' | 'it';
type Direction = 'rtl' | 'ltr';

interface LanguageContextType {
  language: Language;
  direction: Direction;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  fa: {
    app_title: 'حسابرس‌یار',
    app_subtitle: 'هوش مصنوعی حسابرسی تیمیار',
    nav_dashboard: 'داشبورد اصلی',
    nav_chat: 'گفتگو با هوش مصنوعی',
    nav_finetuning: 'تنظیم دقیق مدل (Fine-tune)',
    nav_resources: 'منابع و نمونه‌ها (۱۴۰۴)',
    nav_wp: 'پنل مدیریت (طرح وردپرس)',
    nav_steel: 'حسابرسی آهن‌آلات (استیل آنلاین)',
    stats_today: 'آمار عملکرد امروز',
    role_manager: 'مدیر حسابرسی',
    stat_docs: 'سندهای بررسی شده',
    stat_discrepancies: 'مغایرت‌های کشف شده',
    stat_fraud: 'موارد تقلب (جدید)',
    stat_score: 'امتیاز کنترل داخلی',
    
    // Fine Tuning Studio
    ft_tab_studio: 'استودیو آموزش',
    ft_tab_dashboard: 'داشبورد نتایج (W&B)',
    ft_studio_title: 'استودیو تنظیم دقیق مدل (Fine-Tuning)',
    ft_studio_desc: 'ساخت مدل‌های اختصاصی ضدتقلب با استفاده از دیتاست‌های JAR 2020',
    ft_dash_title: 'داشبورد آزمایش‌ها (Experiments)',
    ft_dash_desc: 'پایش، مقایسه و تحلیل نتایج آزمایش‌های مدل‌سازی (Experiment Tracking)',
    ft_connect_wb: 'اتصال زنده به Weights & Biases',
    ft_connect_desc: 'تمام تحلیل‌ها و فاین‌تیون‌ها در داشبورد حرفه‌ای ثبت می‌شود.',
    ft_view_dash: 'مشاهده داشبورد زنده',
    ft_step_1: 'آپلود داده‌ها',
    ft_drop_file: 'فایل CSV را اینجا رها کنید',
    ft_test_data: 'تست با دیتاست JAR 2020 (Auto-Load)',
    ft_step_2: 'تنظیمات مدل',
    ft_model_name: 'نام مدل',
    ft_epochs: 'Epochs',
    ft_batch_size: 'Batch Size',
    ft_start_btn: 'شروع فاین‌تیون',
    ft_training: 'در حال آموزش...',
    ft_progress: 'پیشرفت آموزش',
    ft_logs: 'لاگ‌های سیستم',
    ft_convergence: 'نمودار همگرایی (Loss & Accuracy)',
    
    // Fine Tuning Dashboard
    ft_kpi_runs: 'تعداد آزمایش‌ها',
    ft_kpi_acc: 'بهترین دقت (Accuracy)',
    ft_kpi_time: 'کل زمان آموزش (GPU)',
    ft_kpi_res: 'مصرف منابع سیستم',
    ft_list_title: 'لیست آزمایش‌ها (Runs)',
    ft_search: 'جستجو...',
    ft_col_name: 'نام',
    ft_col_acc: 'دقت',
    ft_chart_metrics: 'مقایسه روند آموزش (Training Metrics)',
    ft_chart_pred: 'پیش‌نمایش پیش‌بینی‌ها (Predictions)',
    ft_col_input: 'متن تراکنش (Input)',
    ft_col_label: 'برچسب واقعی',
    ft_sys_metrics: 'وضعیت منابع سیستم (System Metrics)',
    
    // Resources & Templates
    res_title: 'مرکز دانش و نمونه فرم‌های مالی ۱۴۰۴',
    res_subtitle: 'استانداردهای حسابداری جدید و فایل‌های نمونه (شُماران سیستم)',
    res_sec_templates: 'دانلود نمونه صورت‌های مالی (اکسل و PDF)',
    res_sec_definitions: 'تعاریف پایه و استانداردهای جدید',
    res_dl_excel: 'دانلود فایل اکسل نمونه (۱۴۰۴)',
    res_dl_pdf: 'دانلود فایل PDF نمونه',
    res_def_balance: 'ترازنامه (Balance Sheet)',
    res_desc_balance: 'گزارش دارایی‌ها، بدهی‌ها و حقوق صاحبان سهام در یک تاریخ خاص.',
    res_def_pl: 'صورت سود و زیان (P&L)',
    res_desc_pl: 'نمایش عملکرد مالی، درآمد و هزینه‌ها در یک دوره زمانی مشخص.',
    res_def_cash: 'صورت جریان وجوه نقد',
    res_desc_cash: 'تحلیل نقدینگی و نمایش جریان ورودی و خروجی پول نقد سازمان.',
    res_erp_title: 'یکپارچگی با ERP',
    res_erp_desc: 'تولید خودکار این گزارش‌ها از طریق اتصال به نرم‌افزار ShAuto ERP و تیمیار.',
    
    // Dashboard & App
    dash_live: 'پایش لحظه‌ای',
    dash_static: 'گزارشات کلی',
    dash_planning: 'برنامه‌ریزی حسابرسی',
    dash_executive: 'مدیریت اجرایی',
    chat_placeholder: 'سوالی بپرسید یا سندی برای بررسی آپلود کنید...',
    chat_send: 'ارسال',
    chat_clear: 'پاکسازی',
    chat_processing: 'در حال پردازش...',
    chat_welcome: 'سوالی بپرسید یا سندی برای بررسی آپلود کنید.',
    chat_response: 'پاسخ حسابرس‌یار',

    // WP Dashboard
    wp_dashboard: 'پیشخوان',
    wp_home: 'خانه',
    wp_updates: 'به‌روزرسانی‌ها',
    wp_posts: 'نوشته‌ها (اسناد)',
    wp_media: 'رسانه (مدارک)',
    wp_pages: 'برگه‌ها (گزارشات)',
    wp_comments: 'دیدگاه‌ها',
    wp_appearance: 'نمایش',
    wp_plugins: 'افزونه‌ها (ماژول‌ها)',
    wp_users: 'کاربران',
    wp_tools: 'ابزارها',
    wp_settings: 'تنظیمات',
    wp_welcome_title: 'به حسابرس‌یار خوش آمدید!',
    wp_welcome_subtitle: 'ما بهترین ابزارهای حسابرسی هوشمند را برای شما فراهم کرده‌ایم.',
    wp_at_a_glance: 'در یک نگاه',
    wp_activity: 'فعالیت',
    wp_quick_draft: 'پیش‌نویس سریع',
    wp_news: 'اخبار و رویدادهای تیمیار',
    wp_title_placeholder: 'عنوان',
    wp_content_placeholder: 'چه چیزی در ذهن دارید؟',
    wp_save_draft: 'ذخیره پیش‌نویس',
    wp_github_project: 'وضعیت پروژه گیت‌هاب',
    wp_gh_branch: 'شاخه فعلی',
    wp_gh_sync: 'وضعیت همگام‌سازی',
    wp_gh_last_commit: 'آخرین کامیت',
    wp_gh_view_repo: 'مشاهده مخزن',
  },
  en: {
    app_title: 'HesabrasYar',
    app_subtitle: 'Teamyar Audit AI',
    nav_dashboard: 'Main Dashboard',
    nav_chat: 'AI Chat',
    nav_finetuning: 'Fine-tuning',
    nav_resources: 'Resources & Templates',
    nav_wp: 'Admin Panel (WP Style)',
    nav_steel: 'Steel Audit (Steel Online)',
    stats_today: 'Today\'s Stats',
    role_manager: 'Audit Manager',
    stat_docs: 'Docs Reviewed',
    stat_discrepancies: 'Discrepancies Found',
    stat_fraud: 'Fraud Cases (New)',
    stat_score: 'Internal Control Score',
    
    ft_tab_studio: 'Training Studio',
    ft_tab_dashboard: 'Results Dashboard (W&B)',
    ft_studio_title: 'Fine-Tuning Studio',
    ft_studio_desc: 'Build custom anti-fraud models using JAR 2020 datasets',
    ft_dash_title: 'Experiments Dashboard',
    ft_dash_desc: 'Track, compare, and visualize modeling experiments',
    ft_connect_wb: 'Live Connect to Weights & Biases',
    ft_connect_desc: 'All analytics and fine-tuning logs are saved to the pro dashboard.',
    ft_view_dash: 'View Live Dashboard',
    ft_step_1: 'Upload Data',
    ft_drop_file: 'Drop CSV file here',
    ft_test_data: 'Test with JAR 2020 Dataset',
    ft_step_2: 'Model Configuration',
    ft_model_name: 'Model Name',
    ft_epochs: 'Epochs',
    ft_batch_size: 'Batch Size',
    ft_start_btn: 'Start Fine-tuning',
    ft_training: 'Training...',
    ft_progress: 'Training Progress',
    ft_logs: 'System Logs',
    ft_convergence: 'Convergence Chart (Loss & Accuracy)',
    
    ft_kpi_runs: 'Total Runs',
    ft_kpi_acc: 'Best Accuracy',
    ft_kpi_time: 'Total GPU Time',
    ft_kpi_res: 'System Resource Usage',
    ft_list_title: 'Experiments List (Runs)',
    ft_search: 'Search...',
    ft_col_name: 'Name',
    ft_col_acc: 'Accuracy',
    ft_chart_metrics: 'Training Metrics Comparison',
    ft_chart_pred: 'Predictions Visualizer',
    ft_col_input: 'Input Transaction',
    ft_col_label: 'True Label',
    ft_sys_metrics: 'System Metrics',

    res_title: 'Knowledge Base & Financial Templates 1404',
    res_subtitle: 'New Accounting Standards and Sample Files (Shomaran System)',
    res_sec_templates: 'Download Financial Statements (Excel & PDF)',
    res_sec_definitions: 'Definitions & New Standards',
    res_dl_excel: 'Download Sample Excel (1404)',
    res_dl_pdf: 'Download Sample PDF',
    res_def_balance: 'Balance Sheet',
    res_desc_balance: 'Report on assets, liabilities, and equity at a specific date.',
    res_def_pl: 'Profit & Loss (P&L)',
    res_desc_pl: 'Shows financial performance, revenue, and expenses over a period.',
    res_def_cash: 'Cash Flow Statement',
    res_desc_cash: 'Liquidity analysis showing cash inflows and outflows.',
    res_erp_title: 'ERP Integration',
    res_erp_desc: 'Automate these reports by connecting to ShAuto ERP and Teamyar.',
    
    dash_live: 'Live Monitoring',
    dash_static: 'General Reports',
    dash_planning: 'Audit Planning',
    dash_executive: 'Executive Mgmt',
    chat_placeholder: 'Ask a question or upload a document...',
    chat_send: 'Send',
    chat_clear: 'Clear',
    chat_processing: 'Processing...',
    chat_welcome: 'Ask a question or upload a document to review.',
    chat_response: 'HesabrasYar Response',

    // WP Dashboard
    wp_dashboard: 'Dashboard',
    wp_home: 'Home',
    wp_updates: 'Updates',
    wp_posts: 'Posts (Audits)',
    wp_media: 'Media (Evidence)',
    wp_pages: 'Pages (Reports)',
    wp_comments: 'Comments',
    wp_appearance: 'Appearance',
    wp_plugins: 'Plugins (Modules)',
    wp_users: 'Users',
    wp_tools: 'Tools',
    wp_settings: 'Settings',
    wp_welcome_title: 'Welcome to HesabrasYar!',
    wp_welcome_subtitle: 'We’ve assembled the best intelligent audit tools for you.',
    wp_at_a_glance: 'At a Glance',
    wp_activity: 'Activity',
    wp_quick_draft: 'Quick Draft',
    wp_news: 'Teamyar Events and News',
    wp_title_placeholder: 'Title',
    wp_content_placeholder: 'What’s on your mind?',
    wp_save_draft: 'Save Draft',
    wp_github_project: 'GitHub Project Status',
    wp_gh_branch: 'Current Branch',
    wp_gh_sync: 'Sync Status',
    wp_gh_last_commit: 'Last Commit',
    wp_gh_view_repo: 'View Repository',
  },
  ar: {
    app_title: 'حسابرس‌یار',
    app_subtitle: 'مساعد التدقيق الذكي',
    nav_dashboard: 'لوحة القيادة',
    nav_chat: 'الدردشة مع الذكاء الاصطناعي',
    nav_finetuning: 'الضبط الدقيق (Fine-tune)',
    nav_resources: 'الموارد والنماذج (1404)',
    nav_wp: 'لوحة الإدارة (نمط WP)',
    nav_steel: 'تدقيق الصلب (Steel Online)',
    stats_today: 'إحصائيات اليوم',
    role_manager: 'مدير التدقيق',
    stat_docs: 'المستندات المراجعة',
    stat_discrepancies: 'الفروقات المكتشفة',
    stat_fraud: 'حالات الاحتيال (جديد)',
    stat_score: 'درجة الرقابة الداخلية',
    
    ft_tab_studio: 'استوديو التدريب',
    ft_tab_dashboard: 'لوحة النتائج (W&B)',
    ft_studio_title: 'استودیو الضبط الدقيق',
    ft_studio_desc: 'بناء نماذج مخصصة لمكافحة الاحتيال',
    ft_dash_title: 'لوحة التجارب',
    ft_dash_desc: 'تتبع ومقارنة نتائج النمذجة',
    ft_connect_wb: 'الاتصال بـ Weights & Biases',
    ft_connect_desc: 'يتم حفظ جميع التحليلات في اللوحة الاحترافية.',
    ft_view_dash: 'عرض اللوحة الحية',
    ft_step_1: 'تحميل البيانات',
    ft_drop_file: 'أفلت ملف CSV هنا',
    ft_test_data: 'اختبار مع بيانات JAR 2020',
    ft_step_2: 'إعدادات النموذج',
    ft_model_name: 'اسم النموذج',
    ft_epochs: 'Epochs',
    ft_batch_size: 'Batch Size',
    ft_start_btn: 'بدء الضبط الدقيق',
    ft_training: 'جاري التدريب...',
    ft_progress: 'تقدم التدريب',
    ft_logs: 'سجلات النظام',
    ft_convergence: 'مخطط التقارب (Loss & Accuracy)',
    
    ft_kpi_runs: 'عدد التجارب',
    ft_kpi_acc: 'أفضل دقة',
    ft_kpi_time: 'وقت GPU الكلي',
    ft_kpi_res: 'استخدام الموارد',
    ft_list_title: 'قائمة التجارب',
    ft_search: 'بحث...',
    ft_col_name: 'الاسم',
    ft_col_acc: 'الدقة',
    ft_chart_metrics: 'مقارنة مقاييس التدريب',
    ft_chart_pred: 'معاين التوقعات',
    ft_col_input: 'معاملة الإدخال',
    ft_col_label: 'التسمية الحقيقية',
    ft_sys_metrics: 'مقاييس النظام',

    res_title: 'قاعدة المعرفة والنماذج المالية',
    res_subtitle: 'معايير المحاسبة الجديدة وملفات العينة',
    res_sec_templates: 'تحميل القوائم المالية',
    res_sec_definitions: 'التعاريف والمعايير',
    res_dl_excel: 'تحميل نموذج Excel',
    res_dl_pdf: 'تحميل نموذج PDF',
    res_def_balance: 'الميزانية العمومية',
    res_desc_balance: 'تقرير عن الأصول والخصوم وحقوق الملكية.',
    res_def_pl: 'بيان الربح والخسارة',
    res_desc_pl: 'يظهر الأداء المالي والإيرادات والمصروفات.',
    res_def_cash: 'بيان التدفق النقدي',
    res_desc_cash: 'تحلیل السیولة وعرض التدفقات النقدیة.',
    res_erp_title: 'تكامل ERP',
    res_erp_desc: 'أتمتة هذه التقارير عبر الاتصال بـ ShAuto ERP.',

    dash_live: 'المراقبة الحية',
    dash_static: 'التقارير العامة',
    dash_planning: 'تخطيط التدقيق',
    dash_executive: 'الإدارة التنفيذية',
    chat_placeholder: 'اطرح سؤالاً أو قم بتحميل مستند...',
    chat_send: 'إرسال',
    chat_clear: 'مسح',
    chat_processing: 'جاري المعالجة...',
    chat_welcome: 'اطرح سؤالاً أو قم بتحميل مستند للمراجعة.',
    chat_response: 'رد حسابرس‌یار',

    wp_dashboard: 'الرئيسية',
    wp_home: 'منزل',
    wp_updates: 'التحديثات',
    wp_posts: 'مقالات (تدقيق)',
    wp_media: 'وسائط',
    wp_pages: 'صفحات (تقارير)',
    wp_comments: 'تعليقات',
    wp_appearance: 'مظهر',
    wp_plugins: 'إضافات',
    wp_users: 'أعضاء',
    wp_tools: 'أدوات',
    wp_settings: 'إعدادات',
    wp_welcome_title: 'مرحباً بك في حسابرس‌یار!',
    wp_welcome_subtitle: 'أدوات التدقيق الذكي في مكان واحد.',
    wp_at_a_glance: 'لمحة سريعة',
    wp_activity: 'نشاط',
    wp_quick_draft: 'مسودة سريعة',
    wp_news: 'أخبار تیمیار',
    wp_title_placeholder: 'عنوان',
    wp_content_placeholder: 'ماذا يدور في ذهنك؟',
    wp_save_draft: 'حفظ المسودة',
    wp_github_project: 'حالة مشروع GitHub',
    wp_gh_branch: 'الفرع الحالي',
    wp_gh_sync: 'حالة المزامنة',
    wp_gh_last_commit: 'آخر التزام',
    wp_gh_view_repo: 'عرض المستودع',
  },
  sv: {
    app_title: 'HesabrasYar',
    app_subtitle: 'Teamyar Revision AI',
    nav_dashboard: 'Instrumentpanel',
    nav_chat: 'AI-chatt',
    nav_finetuning: 'Finjustering',
    nav_resources: 'Resurser & Mallar',
    nav_wp: 'Adminpanel (WP-stil)',
    nav_steel: 'Stålrevision (Steel Online)',
    stats_today: 'Dagens statistik',
    role_manager: 'Revisionschef',
    stat_docs: 'Granskade dokument',
    stat_discrepancies: 'Upptäckta avvikelser',
    stat_fraud: 'Bedrägerifall (Nya)',
    stat_score: 'Internkontrollpoäng',
    
    ft_tab_studio: 'Träningsstudio',
    ft_tab_dashboard: 'Resultatpanel (W&B)',
    ft_studio_title: 'Studio för Finjustering',
    ft_studio_desc: 'Bygg anpassade modeller för bedrägeribekämpning',
    ft_dash_title: 'Experimentpanel',
    ft_dash_desc: 'Spåra, jämför och visualisera modelleringsexperiment',
    ft_connect_wb: 'Anslut till Weights & Biases',
    ft_connect_desc: 'Alla analyser sparas i instrumentpanelen.',
    ft_view_dash: 'Visa live-panel',
    ft_step_1: 'Ladda upp data',
    ft_drop_file: 'Släpp CSV-fil här',
    ft_test_data: 'Testa med JAR 2020 Dataset',
    ft_step_2: 'Modellkonfiguration',
    ft_model_name: 'Modellnamn',
    ft_epochs: 'Epoker',
    ft_batch_size: 'Batchstorlek',
    ft_start_btn: 'Starta finjustering',
    ft_training: 'Tränar...',
    ft_progress: 'Träningsframsteg',
    ft_logs: 'Systemloggar',
    ft_convergence: 'Konvergensdiagram',
    
    ft_kpi_runs: 'Totalt antal körningar',
    ft_kpi_acc: 'Bästa noggrannhet',
    ft_kpi_time: 'Total GPU-tid',
    ft_kpi_res: 'Resursanvändning',
    ft_list_title: 'Experimentlista',
    ft_search: 'Sök...',
    ft_col_name: 'Namn',
    ft_col_acc: 'Noggrannhet',
    ft_chart_metrics: 'Jämförelse av mätvärden',
    ft_chart_pred: 'Förutsägelsevisualiserare',
    ft_col_input: 'Indata',
    ft_col_label: 'Etikett',
    ft_sys_metrics: 'Systemmätvärden',

    res_title: 'Resurser & Finansiella Mallar',
    res_subtitle: 'Nya redovisningsstandarder och exempelfiler',
    res_sec_templates: 'Ladda ner finansiella rapporter',
    res_sec_definitions: 'Definitioner & Standarder',
    res_dl_excel: 'Ladda ner Excel-mall',
    res_dl_pdf: 'Ladda ner PDF-mall',
    res_def_balance: 'Balansräkning',
    res_desc_balance: 'Rapport om tillgångar, skulder och eget kapital.',
    res_def_pl: 'Resultaträkning',
    res_desc_pl: 'Visar finansiellt resultat, intäkter och kostnader.',
    res_def_cash: 'Kassaflödesanalys',
    res_desc_cash: 'Likviditetsanalys som visar in- och utbetalningar.',
    res_erp_title: 'ERP-integration',
    res_erp_desc: 'Automatisera dessa rapporter via ShAuto ERP.',

    dash_live: 'Live-övervakning',
    dash_static: 'Allmänna rapporter',
    dash_planning: 'Revisionsplanering',
    dash_executive: 'Ledning',
    chat_placeholder: 'Ställ en fråga eller ladda upp ett dokument...',
    chat_send: 'Skicka',
    chat_clear: 'Rensa',
    chat_processing: 'Bearbetar...',
    chat_welcome: 'Ställ en fråga eller ladda upp ett dokument för granskning.',
    chat_response: 'HesabrasYar Svar',

    wp_dashboard: 'Instrumentpanel',
    wp_home: 'Hem',
    wp_updates: 'Uppdateringar',
    wp_posts: 'Inlägg',
    wp_media: 'Media',
    wp_pages: 'Sidor',
    wp_comments: 'Kommentarer',
    wp_appearance: 'Utseende',
    wp_plugins: 'Tillägg',
    wp_users: 'Användare',
    wp_tools: 'Verktyg',
    wp_settings: 'Inställningar',
    wp_welcome_title: 'Välkommen till HesabrasYar!',
    wp_welcome_subtitle: 'Vi har samlat de bästa revisionsverktygen för dig.',
    wp_at_a_glance: 'Överblick',
    wp_activity: 'Aktivitet',
    wp_quick_draft: 'Snabbutkast',
    wp_news: 'Teamyar Nyheter',
    wp_title_placeholder: 'Rubrik',
    wp_content_placeholder: 'Vad tänker du på?',
    wp_save_draft: 'Spara utkast',
    wp_github_project: 'GitHub Projektstatus',
    wp_gh_branch: 'Aktuell gren',
    wp_gh_sync: 'Synkroniseringsstatus',
    wp_gh_last_commit: 'Senaste commit',
    wp_gh_view_repo: 'Visa arkiv',
  },
  tr: {
    app_title: 'HesabrasYar',
    app_subtitle: 'Teamyar Denetim Yapay Zekası',
    nav_dashboard: 'Ana Panel',
    nav_chat: 'Yapay Zeka Sohbeti',
    nav_finetuning: 'İnce Ayar (Fine-tuning)',
    nav_resources: 'Kaynaklar & Şablonlar',
    nav_wp: 'Yönetici Paneli (WP)',
    nav_steel: 'Çelik Denetimi (Steel Online)',
    stats_today: 'Bugünün İstatistikleri',
    role_manager: 'Denetim Müdürü',
    stat_docs: 'İncelenen Belgeler',
    stat_discrepancies: 'Bulunan Uyuşmazlıklar',
    stat_fraud: 'Dolandırıcılık Vakaları (Yeni)',
    stat_score: 'İç Kontrol Puanı',
    
    ft_tab_studio: 'Eğitim Stüdyosu',
    ft_tab_dashboard: 'Sonuç Paneli (W&B)',
    ft_studio_title: 'İnce Ayar Stüdyosu',
    ft_studio_desc: 'JAR 2020 veri setlerini kullanarak özel modeller oluşturun',
    ft_dash_title: 'Deney Paneli',
    ft_dash_desc: 'Modelleme deneylerini izleyin, karşılaştırın ve görselleştirin',
    ft_connect_wb: 'Weights & Biases Bağlantısı',
    ft_connect_desc: 'Tüm analizler profesyonel panele kaydedilir.',
    ft_view_dash: 'Canlı Paneli Görüntüle',
    ft_step_1: 'Veri Yükle',
    ft_drop_file: 'CSV dosyasını buraya bırakın',
    ft_test_data: 'JAR 2020 Veri Seti ile Test Et',
    ft_step_2: 'Model Yapılandırması',
    ft_model_name: 'Model Adı',
    ft_epochs: 'Epochs',
    ft_batch_size: 'Batch Size',
    ft_start_btn: 'İnce Ayarı Başlat',
    ft_training: 'Eğitiliyor...',
    ft_progress: 'Eğitim İlerlemesi',
    ft_logs: 'Sistem Günlükleri',
    ft_convergence: 'Yakınsama Grafiği',
    
    ft_kpi_runs: 'Toplam Koşu',
    ft_kpi_acc: 'En İyi Doğruluk',
    ft_kpi_time: 'Toplam GPU Süresi',
    ft_kpi_res: 'Sistem Kaynak Kullanımı',
    ft_list_title: 'Deney Listesi',
    ft_search: 'Ara...',
    ft_col_name: 'İsim',
    ft_col_acc: 'Doğruluk',
    ft_chart_metrics: 'Eğitim Metrikleri Karşılaştırması',
    ft_chart_pred: 'Tahmin Görselleştirici',
    ft_col_input: 'Giriş İşlemi',
    ft_col_label: 'Gerçek Etiket',
    ft_sys_metrics: 'Sistem Metrikleri',

    res_title: 'Bilgi Tabanı ve Finansal Şablonlar',
    res_subtitle: 'Yeni Muhasebe Standartları ve Örnek Dosyalar',
    res_sec_templates: 'Finansal Tabloları İndir',
    res_sec_definitions: 'Tanımlar ve Standartlar',
    res_dl_excel: 'Excel Şablonunu İndir',
    res_dl_pdf: 'PDF Şablonunu İndir',
    res_def_balance: 'Bilanço',
    res_desc_balance: 'Varlıklar, borçlar ve özkaynak raporu.',
    res_def_pl: 'Kar ve Zarar Tablosu',
    res_desc_pl: 'Finansal performans, gelir ve giderleri gösterir.',
    res_def_cash: 'Nakit Akış Tablosu',
    res_desc_cash: 'Nakit giriş ve çıkışlarını gösteren likidite analizi.',
    res_erp_title: 'ERP Entegrasyonu',
    res_erp_desc: 'ShAuto ERP bağlantısı ile bu raporları otomatikleştirin.',

    dash_live: 'Canlı İzleme',
    dash_static: 'Genel Raporlar',
    dash_planning: 'Denetim Planlama',
    dash_executive: 'Yönetici Paneli',
    chat_placeholder: 'Bir soru sorun veya belge yükleyin...',
    chat_send: 'Gönder',
    chat_clear: 'Temizle',
    chat_processing: 'İşleniyor...',
    chat_welcome: 'İnceleme için bir soru sorun veya belge yükleyin.',
    chat_response: 'HesabrasYar Yanıtı',

    wp_dashboard: 'Başlangıç',
    wp_home: 'Ev',
    wp_updates: 'Güncellemeler',
    wp_posts: 'Yazılar',
    wp_media: 'Ortam',
    wp_pages: 'Sayfalar',
    wp_comments: 'Yorumlar',
    wp_appearance: 'Görünüm',
    wp_plugins: 'Eklentiler',
    wp_users: 'Kullanıcılar',
    wp_tools: 'Araçlar',
    wp_settings: 'Ayarlar',
    wp_welcome_title: 'HesabrasYar\'a Hoş Geldiniz!',
    wp_welcome_subtitle: 'Sizin için en iyi denetim araçlarını bir araya getirdik.',
    wp_at_a_glance: 'Bir Bakışta',
    wp_activity: 'Etkinlik',
    wp_quick_draft: 'Hızlı Taslak',
    wp_news: 'Teamyar Haberleri',
    wp_title_placeholder: 'Başlık',
    wp_content_placeholder: 'Aklınızda ne var?',
    wp_save_draft: 'Taslağı Kaydet',
    wp_github_project: 'GitHub Proje Durumu',
    wp_gh_branch: 'Mevcut Şube',
    wp_gh_sync: 'Senkronizasyon Durumu',
    wp_gh_last_commit: 'Son Taahhüt',
    wp_gh_view_repo: 'Depoyu Görüntüle',
  },
  it: {
    app_title: 'HesabrasYar',
    app_subtitle: 'Teamyar Audit AI',
    nav_dashboard: 'Dashboard Principale',
    nav_chat: 'Chat AI',
    nav_finetuning: 'Fine-tuning',
    nav_resources: 'Risorse e Modelli',
    nav_wp: 'Pannello Admin (WP)',
    nav_steel: 'Audit Acciaio (Steel Online)',
    stats_today: 'Statistiche di Oggi',
    role_manager: 'Responsabile Audit',
    stat_docs: 'Documenti Revisionati',
    stat_discrepancies: 'Discrepanze Trovate',
    stat_fraud: 'Casi di Frode (Nuovi)',
    stat_score: 'Punteggio Controllo Interno',
    
    ft_tab_studio: 'Studio di Training',
    ft_tab_dashboard: 'Dashboard Risultati (W&B)',
    ft_studio_title: 'Studio di Fine-Tuning',
    ft_studio_desc: 'Costruisci modelli antifrode personalizzati',
    ft_dash_title: 'Dashboard Esperimenti',
    ft_dash_desc: 'Traccia, confronta e visualizza esperimenti',
    ft_connect_wb: 'Connetti a Weights & Biases',
    ft_connect_desc: 'Tutte le analisi vengono salvate nella dashboard.',
    ft_view_dash: 'Vedi Dashboard Live',
    ft_step_1: 'Carica Dati',
    ft_drop_file: 'Rilascia file CSV qui',
    ft_test_data: 'Testa con Dataset JAR 2020',
    ft_step_2: 'Configurazione Modello',
    ft_model_name: 'Nome Modello',
    ft_epochs: 'Epochs',
    ft_batch_size: 'Batch Size',
    ft_start_btn: 'Avvia Fine-tuning',
    ft_training: 'Training in corso...',
    ft_progress: 'Progresso Training',
    ft_logs: 'Log di Sistema',
    ft_convergence: 'Grafico Convergenza',
    
    ft_kpi_runs: 'Esecuzioni Totali',
    ft_kpi_acc: 'Miglior Accuratezza',
    ft_kpi_time: 'Tempo GPU Totale',
    ft_kpi_res: 'Uso Risorse Sistema',
    ft_list_title: 'Lista Esperimenti',
    ft_search: 'Cerca...',
    ft_col_name: 'Nome',
    ft_col_acc: 'Accuratezza',
    ft_chart_metrics: 'Confronto Metriche',
    ft_chart_pred: 'Visualizzatore Predizioni',
    ft_col_input: 'Input Transazione',
    ft_col_label: 'Etichetta Reale',
    ft_sys_metrics: 'Metriche di Sistema',

    res_title: 'Knowledge Base & Modelli Finanziari',
    res_subtitle: 'Nuovi Standard Contabili e File di Esempio',
    res_sec_templates: 'Scarica Bilanci',
    res_sec_definitions: 'Definizioni e Standard',
    res_dl_excel: 'Scarica Modello Excel',
    res_dl_pdf: 'Scarica Modello PDF',
    res_def_balance: 'Stato Patrimoniale',
    res_desc_balance: 'Report su attività, passività e patrimonio netto.',
    res_def_pl: 'Conto Economico (P&L)',
    res_desc_pl: 'Mostra performance finanziaria, ricavi e costi.',
    res_def_cash: 'Rendiconto Finanziario',
    res_desc_cash: 'Analisi liquidità che mostra flussi in entrata e uscita.',
    res_erp_title: 'Integrazione ERP',
    res_erp_desc: 'Automatizza questi report connettendo ShAuto ERP.',

    dash_live: 'Monitoraggio Live',
    dash_static: 'Report Generali',
    dash_planning: 'Pianificazione Audit',
    dash_executive: 'Gestione Esecutiva',
    chat_placeholder: 'Fai una domanda o carica un documento...',
    chat_send: 'Invia',
    chat_clear: 'Pulisci',
    chat_processing: 'Elaborazione...',
    chat_welcome: 'Fai una domanda o carica un documento da revisionare.',
    chat_response: 'Risposta HesabrasYar',

    wp_dashboard: 'Bacheca',
    wp_home: 'Home',
    wp_updates: 'Aggiornamenti',
    wp_posts: 'Articoli',
    wp_media: 'Media',
    wp_pages: 'Pagine',
    wp_comments: 'Commenti',
    wp_appearance: 'Aspetto',
    wp_plugins: 'Plugin',
    wp_users: 'Utenti',
    wp_tools: 'Strumenti',
    wp_settings: 'Impostazioni',
    wp_welcome_title: 'Benvenuto in HesabrasYar!',
    wp_welcome_subtitle: 'Abbiamo riunito i migliori strumenti di audit per te.',
    wp_at_a_glance: 'In sintesi',
    wp_activity: 'Attività',
    wp_quick_draft: 'Bozza rapida',
    wp_news: 'Novità Teamyar',
    wp_title_placeholder: 'Titolo',
    wp_content_placeholder: 'Cosa ti passa per la testa?',
    wp_save_draft: 'Salva bozza',
    wp_github_project: 'Stato Progetto GitHub',
    wp_gh_branch: 'Ramo Corrente',
    wp_gh_sync: 'Stato Sincronizzazione',
    wp_gh_last_commit: 'Ultimo Commit',
    wp_gh_view_repo: 'Vedi Repository',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('fa');
  const [direction, setDirection] = useState<Direction>('rtl');

  useEffect(() => {
    const isRTL = language === 'fa' || language === 'ar';
    const dir = isRTL ? 'rtl' : 'ltr';
    setDirection(dir);
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, direction, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
